### ISSUE TITLE
Update to newest guzzle

### ISSUE THREAD

**Issue by mablae** [richardfullmer/php-rabbitmq-management-api#4]
or even use Httplug: http://docs.php-http.org/en/latest/httplug/introduction.html

@richardfullmer I would create a PR for it. Just let me know what you think.

**Comment by Nyholm** [comment]
:+1: for HTTPlug and interoperability.

**Comment by richardfullmer** [comment]
Yes, I've been meaning to do this too, since guzzle/guzzle is abandoned... just haven't had the time.

**Comment by mablae** [comment]
Okay, I will go for it then. We can work together if you want to. I could start on the weekend.

**Comment by Nyholm** [comment]
Let me know if you want any help or reviews. Im happy to contribute.

**Comment by richardfullmer** [comment]
Took a first crack at this at #6, let me know if this implementation will work ok for you.
